name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: docker login, build and push
        uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t varunrd/multi-client ./client
      - run: docker build -t varunrd/multi-nginx ./nginx
      - run: docker build -t varunrd/multi-server ./server
      - run: docker build -t varunrd/multi-worker ./worker
      - run: docker push varunrd/multi-client
      - run: docker push varunrd/multi-nginx
      - run: docker push varunrd/multi-server
      - run: docker push varunrd/multi-worker